# Deploy last pushed Jupyter Book docs (_build/) to the docs branch for GH pages

name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push-docs-dir:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Add docutils to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/paddy_docutils/" >> $GITHUB_ENV
          
      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Add CNAME
        run: |
          echo "paddy.pfiers.net" > _build/html/CNAME

      - name: Add .nojekyll
        run: |
          touch _build/html/.nojekyll

      - name: Push docs dir
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: "_build/html"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
